services:
  citybase-flask-app:
    profiles: [development]
    command: ["/usr/local/bin/python", "/root/app/app.py"]
    container_name: citybase-flask-app-development
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/root/app
    env_file:
      - .env

  citybase-gunicorn-app-production:
    profiles: [production]
    command:
      [
        "gunicorn",
        "--threads",
        "4",
        "--workers",
        "2",
        "--bind",
        "0.0.0.0:5000",
        "app:app",
      ]
    working_dir: /root/app
    container_name: citybase-gunicorn-app-production
    build: .
    restart: unless-stopped
    ports:
      - "172.17.0.1:13100:5000"
    volumes:
      - .:/root/app
    env_file:
      - .env

  citybase-gunicorn-app-staging:
    profiles: [staging]
    command:
      [
        "gunicorn",
        "--threads",
        "4",
        "--workers",
        "2",
        "--bind",
        "0.0.0.0:5000",
        "app:app",
      ]
    working_dir: /root/app
    container_name: citybase-gunicorn-app-staging
    build: .
    restart: unless-stopped
    ports:
      - "172.17.0.1:13101:5000"
    volumes:
      - .:/root/app
    env_file:
      - .env

  citybase-gunicorn-uat:
    profiles: [uat]
    command:
      [
        "gunicorn",
        "--threads",
        "4",
        "--workers",
        "2",
        "--bind",
        "0.0.0.0:5000",
        "app:app",
      ]
    working_dir: /root/app
    container_name: citybase-gunicorn-app-uat
    build: .
    restart: unless-stopped
    ports:
      - "172.17.0.1:13102:5000"
    volumes:
      - .:/root/app
    env_file:
      - .env
