services:
  citybase-flask-app:
    profiles: [development]
    command: ["/usr/local/bin/python", "/root/app/app.py"]
    container_name: citybase-flask-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/root/app
    env_file:
      - .env
  citybase-gunicorn-app:
    profiles: [production, staging, uat]
    command: ["gunicorn", "--threads", "4", "--workers", "2", "--bind", "0.0.0.0:5000", "app:app"]
    working_dir: /root/app
    build: .
    restart: unless-stopped
    ports:
      - "172.17.0.1:5000:5000"
    volumes:
      - .:/root/app
    env_file:
      - .env
